modLoader="javafml"
loaderVersion="[${loader_version},)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Yunus1903/LocalKeys/issues"

[[mods]]
    modId="localkeys"
    version="${version}"
    displayName="LocalKeys"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/localkeys"
    logoFile="localkeys.png"

    authors="Yunus1903"
    credits=""
    description="A way to localize your keybindings"

[[dependencies.localkeys]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.localkeys]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
